### ISSUE TITLE
Select Model & Tape Fast Load in fuse-libretro (ZX Spectrum)

### ISSUE THREAD

**Issue by Roolandoo** [kivutar/rombundler#12]
Hi,
I'm trying to make ROMBundler work with the fuse-libretro (for ZX Spectrum) but by default it works with slow tape loading (exasperating) and in 48Kb mode.

Is it possible to add options to change it?

**Comment by kivutar** [comment]
OK let me add core options to the feature list.
Is it exposed as a core option?

**Comment by Roolandoo** [comment]
Yes, "Tape Fast Load" and "Model" are core option in fuse-libretro.
Thanks!!

**Comment by kivutar** [comment]
Can you try the v1.8 release please?
You can now add a options.ini
Since it's a .ini, you don't use the double quotes on values.
