### ISSUE TITLE
Assignment of devices to ports

### ISSUE THREAD

**Issue by Roolandoo** [kivutar/rombundler#24]
Hello,
Fuse-libretro works perfectly with Rombundler since you added the Core Options.
The problem now is that Fuse uses the joystick by default.

**Would adding an option to assign the keyboard to a port be possible?**

More information here: https://github.com/libretro/fuse-libretro/issues/117https://github.com/libretro/fuse-libretro/issues/117
Thanks

**Comment by kivutar** [comment]
Yes, but I need to add keyboard support first.

**Comment by Roolandoo** [comment]
Ahhh ok
It would be great because most people play ZX Spectrum with a keyboard.
Thank you.

**Comment by kivutar** [comment]
I added very basic, maybe incomplete keyboard support in master.

**Comment by kivutar** [comment]
I'm creating a release, can you please tell me if this is working for you?

**Comment by Roolandoo** [comment]
Hi,
I tried version 1.15 (because 1.16 isn't for Windows) and the keyboard doesn't work (neither does the joystick now, of course).
I don't know if it was my mistake. Do I have to do any specific settings for the keyboard to work? I have only tested it with fuse_libretro.dll

**Comment by kivutar** [comment]
OK my bad, the windows build failed because of a network error during the automated build...

I'm rebuilding it.

**Comment by kivutar** [comment]
If you can, please send me your ROM, I'll try to see what I'm doing wrong.

**Comment by kivutar** [comment]
They fixed the issue, https://github.com/kivutar/rombundler/releases/download/v1.18/ROMBundler-Windows-1.18.zip is available

**Comment by Roolandoo** [comment]
Thank you very much but the keyboard still does not work. I have tried various ROMs.
I'm sure I'm doing something wrong.
Here is an example ROM: [ROMBundler-Windows-1.18 FUSE.zip](https://github.com/kivutar/rombundler/files/7271716/ROMBundler-Windows-1.18.FUSE.zip)

Greetings and thanks for your effort.

**Comment by kivutar** [comment]
OK, with your rom, I found a way to make it work. I'll commit that asap.

**Comment by kivutar** [comment]
It also happen to fix qbasic on dosbox :)

<img width="912" alt="Screen Shot 2021-10-03 at 01 09 51" src="https://user-images.githubusercontent.com/442722/135727460-98e38448-5294-4a04-b877-624db49b0a43.png">

**Comment by kivutar** [comment]
I released v1.19, I tested it on your game and was able to control the character with the keyboard.

**Comment by Roolandoo** [comment]
It works!! All perfect.

Now all ROMs can be played with the keyboard and also with the Joystick (configuring it in the options.ini).
Brilliant!! Thank you very much for your great work.

Greetings

**Comment by kivutar** [comment]
Thanks for testing it.
