### ISSUE TITLE
MSX

### ISSUE THREAD

**Issue by Roolandoo** [kivutar/rombundler#26]
Hello,
I am very interested in making Rombundler work with games for the classic MSX system.
I tried on Windows with bluemsx_libretro.dll and fmsx_libretro.dll but they don't work.

**Is there a way to make it work or is it just incompatible?**
Greetings and thank you very much.

**Comment by kivutar** [comment]
Indeed, I was able to load an MSX game in Ludo, but not in rombundler. Let me check why...

**Comment by kivutar** [comment]
It's failing here https://github.com/libretro/blueMSX-libretro/blob/master/libretro.c#L983-L985

I tried copying the bluemsx.ini, the bluemsx_history.ini, and setting the right options.ini

I still can't find why it's failing.

**Comment by kivutar** [comment]
OK I could at least launch a ROM by following the instructions here https://docs.libretro.com/library/bluemsx/#bios

Copying the Machines folder.

**Comment by Roolandoo** [comment]
Yes, Yes, Yes. It works !!!
I never would have come up with that solution.
You are great, friend!!!

Thanks a lot.
