### ISSUE TITLE
PSA: Final Burn Alpha 2012 Neo Geo seems to work without issues in ROMBundler

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [kivutar/rombundler#30]
So far I've tested only one game, Pulstar from the Linux build from GOG, but I plan to test more when I get the chance.

I used the Linux build of ROMBundler in Ubuntu 20.04, and I used the fbalpha2012_neogeo_libretro.so build from a few hours ago from https://buildbot.libretro.com/nightly/linux/x86_64/latest/

**Comment by kivutar** [comment]
Good to know, thx
