### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by UserGit-2021** [kivutar/rombundler#31]
Useful project. Weighs less than RetroArch.

**Comment by diegzumillo** [comment]
And it's usable as is already, depending on your goal. I tested on my mega drive project and it works great. I tried implementing a CRT shader but it didn't work; but that was a while ago though

**Comment by kivutar** [comment]
If you want something closer to retroarch but still lighter try https://ludo.libretro.com/

**Comment by BLINXERIZER** [comment]
I love Rombundler.
