### ISSUE TITLE
R button not working

### ISSUE THREAD

**Issue by BLINXERIZER** [kivutar/rombundler#32]
I was trying to play some games that use L/R (not L2/R2) and found R doesn't work at all. L will work but not R and L2/R2 work but those act as turbo buttons and I'm not trying to do that. It seems to be a problem in the script and how you have the controls setup. Not the cores because I used the same exact cores with Ludo and I didn't have the same issue. Tested out with Astal for Sega Saturn (which works great btw aside from the issue because you can change the control setup in the games options menu) and Klonoa 2 for GBA. Because of the 6 button layout of a Saturn controller, apparently the C button get's mapped to R which as I mentioned doesn't work. 

Example: Default controls for Astal has Jump mapped to C and since R doesn't work, you can't jump unless you swap around the buttons.

**Comment by BLINXERIZER** [comment]
Forgot to mention I am using Mednafen_Saturn and MGBA.

**Comment by BLINXERIZER** [comment]
Ok apparently it's doing the samething for SNES games. Tried playing Sparkster using both snes9x and mesen-s. In that game you use L and R to dodge left or right. L works but R doesn't...

**Comment by BLINXERIZER** [comment]
Ugh R button isn't working for PS1 games either... Trying out Gex Enter the Gecko and you use L1 and R1 to rotate the camera. Can rotate left with L1, but can't rotate right with R1.

**Comment by kivutar** [comment]
Then it will be easy to fix, if it's a general issue

**Comment by kivutar** [comment]
I created a new release that should fix the problem on keyboard.

**Comment by BLINXERIZER** [comment]
This just for Keyboard and not controller?

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 4, 2022 at 3:25 PM, Jean-André ***@***.***> wrote:   


I created a new release that should fix the problem on keyboard.

**Comment by kivutar** [comment]
Right, I tested with controllers, on Street Fighters 2 on SNES, and L and R were working fine.
Can you try on this game?
It's possible that we mistake the cause of the problem.

**Comment by kivutar** [comment]
OK I'm now able to reproduce for pads

**Comment by kivutar** [comment]
OK, I found a fix, and pushed it, version v1.22
Thanks for your help!

**Comment by BLINXERIZER** [comment]
> OK, I found a fix, and pushed it, version v1.22 Thanks for your help!

No problem and thank you very much for fixing this! There are so many PS1 games that use the R1 button and were unplayable but now I can finally play them!
